spring:
  application:
    name: journalbackend

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  ai:
    chat:
      client:
        enabled: false

    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        model: claude-haiku-4-5
        temperature: 0.2
        max-tokens: 5000

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
        temperature: 0.2
        max-tokens: 5000